location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: b093a670ffebc6243d2ed1feb79d36e7657cf21c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
