location: .gitman
sources:
- name: realsense
  type: git
  repo: git@nuc7:uav/realsense2_camera
  sparse_paths:
  -
  rev: master
  link: ros_packages/realsense
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: realsense
  type: git
  repo: git@nuc7:uav/realsense2_camera
  sparse_paths:
  -
  rev: f89f256b3dc8faabee16d08a1b7f229ef4ddb226
  link: ros_packages/realsense
  scripts:
  - git submodule update --init --recursive
