location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: 1759e65708f46d9f88050e5b859447299d54fc50
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
