location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: 05be9e4cf5910f773bcf91c2c980a9c40adf0974
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
