location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/realsense-ros.git
    name: realsense-ros
    rev: c656aa612a327487e7a32b78c8d881fa4fa22ae6
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
