location: .gitman
sources:
- name: realsense
  type: git
  repo: git@nuc7:uav/realsense2_camera
  sparse_paths:
  -
  rev: master
  link: ros_packages/realsense
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: realsense
  type: git
  repo: git@nuc7:uav/realsense2_camera
  sparse_paths:
  -
  rev: 58eb9c8251b0f54de4002dd68b7088b82bcc1d66
  link: ros_packages/realsense
  scripts:
  - git submodule update --init --recursive
