location: .gitman
sources:
  - repo: git@github.com:ctu-mrs/realsense-ros
    name: realsense-ros
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/realsense-ros
    links:
      - target: ros_packages/realsense-ros
    scripts:
      - git submodule update --init --recursive
