services:
  realsense:
    image: mrs_realsense:latest
    build: .
    privileged: true
    network_mode: "host"
    volumes:
      - type: bind
        source: ./cfg.yaml
        target: /home/ubuntu/ws/cfg.yaml
        read_only: true
    command: custom_config:=cfg.yaml