gains:
  
  # THOSE ARE THE SOFT GAINS
  pos: {x: 7.0, y: 7.0, z: 7.0}
  vel: {x: 2.4, y: 2.4, z: 3.0}
  ki:  {x: 0.000, y: 0.000, z: 0.001}
  kib: {x: 0.000, y: 0.000, z: 0.0005}

  # THOSE ARE THE TIGHT GAINS
  # pos: {x: 11.0, y: 11.0, z: 9.6}
  # vel: {x: 4.4, y: 4.4, z: 5.6}
  # ki:  {x: 0.009, y: 0.009, z: 0.002}
  # kib: {x: 0.001, y: 0.001, z: 0.001}

max_pos_int: 4.0
max_pos_int_b: 0.5

max_tilt_angle: 0.785
