gains:
  # gains for icp
  # pos: {x: 3.0, y: 3.0, z: 4.0}
  # vel: {x: 2.0, y: 2.0, z: 2.0}
  pos: {x: 1.0, y: 1.0, z: 8.0}
  vel: {x: 1.0, y: 1.0, z: 3.0}

  ki:  {x: 0.000, y: 0.000, z: 0.05}
  kib: {x: 0.000, y: 0.000, z: 0.05}

max_pos_int:   2.5
max_pos_int_b: 0.5

# max_tilt_angle: 0.087
max_tilt_angle: 0.2
