use_rc_failsafe: true
rc_failsafe_threshold: 1500       # [1000, 2000]
rc_failsafe_channel: 8            # indexing from 1
diagnostics_rate: 1               # publish diagnostics at n Hz
diagnostic_tracking_threshold: 1  # [m] distance considered as "in place"

# mrs collision avoidance
mrs_collision_avoidance:
  enable: true
  trajectory_timeout: 2.0 # [s]
  drone_names: [uav1, uav2, uav3, uav4, uav5, uav6, uav7]
  radius: 5.0 # [m]
  altitude_threshold: 2.95 # [m]
  correction: 3.0 # [m]
  predicted_trajectory_publish_rate: 2 # [Hz]
  collision_horizontal_speed_coef: 0.25 # when collision detected, slow down during the manouver
  collision_horizontal_acceleration_coef: 0.5 # when collision detected, keep the acceleration down during the manouvre
  collision_slow_down_before: 10 # when collision detected, slow down this number of steps before it
  collision_slowing_hysteresis: 2.0 # [s] prolonging the slowing

dynamicalModel:
  numberOfStates: 9
  numberOfInputs: 3

  A: [1, 0.01, 0, 0, 0, 0, 0, 0, 0,
      0, 1, 0.01, 0, 0, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0, 0, 0, 0,
      0, 0, 0, 1, 0.01, 0, 0, 0, 0,
      0, 0, 0, 0, 1, 0.01, 0, 0, 0,
      0, 0, 0, 0, 0, 1, 0, 0, 0,
      0, 0, 0, 0, 0, 0, 1, 0.01, 0,
      0, 0, 0, 0, 0, 0, 0, 1, 0.01,
      0, 0, 0, 0, 0, 0, 0, 0, 1]

  B: [0, 0, 0,
      0, 0, 0,
      0.01, 0, 0,
      0, 0, 0,
      0, 0, 0,
      0, 0.01, 0,
      0, 0, 0,
      0, 0, 0,
      0, 0, 0.01]

yawModel:
  numberOfStates: 3
  numberOfInputs: 1

  A: [1, 0.01, 0,
      0, 1, 0.01,
      0, 0, 1]

  B: [0,
      0,
      0.01]

yawTracker:
  yawGain: 1.0
  maxYawRate: 1.0

cvxgenMpc:
  horizon_len: 40 # Horizon length is hardcoded in cvxgen code, this value is used in other parts of the code
  maxTrajectorySize: 5000

  dt: 0.01
  dt2: 0.2

  maxHorizontalSpeed: 8.33
  maxHorizontalAcceleration: 2.33
  maxHorizontalJerk: 3.0

  maxVerticalAscendingSpeed: 2.0
  maxVerticalAscendingAcceleration: 1.0
  maxVerticalAscendingJerk: 3.0

  maxVerticalDescendingSpeed: 1.0
  maxVerticalDescendingAcceleration: 1.0
  maxVerticalDescendingJerk: 1.5

  maxYawRate: 1.0
  maxYawAcceleration: 2.0

  maxAltitude: 20.0
  minAltitude: 1.0

cvxWrapper:
  verbose: false # cvxgen's debug output
  maxNumOfIterations: 30
  Q: [5000, 2000, 0, 5000, 2000, 0]
  R: [500, 500]

cvxWrapperZ:
  verbose: false # cvxgen's debug output
  maxNumOfIterations: 20
  Q: [5000, 2000, 0]
  R: [500]

cvxWrapperYaw:
  verbose: false # cvxgen's debug output
  maxNumOfIterations: 20
  Q: [5000, 2000, 0]
  R: [500]
